CREATE DATABASE STUDENT;
USE STUDENT;
CREATE TABLE STUDENTDETAILS1( 
   STUDENTNAME VARCHAR(20),
   STUDENTUSN INT(9),
   STUDENTATTENDENCE INT(2),
   STUDENTCHECKATTENDENCE INT(9),
   STUDENTFIRTIAMARKS INT(3),
   STUDENTSECONDIAMARKS INT(3),
   STUDENTTHIRDIAMARKS INT(3),
   STUDENTTOTALINTERNALMARKS INT(2),
   STUDENTTOTALEXTERNALMARKS INT(2),
   SUBJECTNAME VARCHAR(10)
);

CREATE DATABASE SCHOOL;
USE SCHOOL;

CREATE TABLE SANTHOM1(
	TRUSTNAME VARCHAR(10),
    PLAYGROUND INT(5),
    LIBRARYNAME VARCHAR(8),
    TOTALTEACHER INT(5),
    TOTALSTUDENT INT(5),
    PRINCIPALNAME VARCHAR(10),
    NONSTAFF INT(3)
);

CREATE DATABASE MOBLIEBRANDS;
USE MOBLIEBRANDS;

CREATE TABLE BRANDS(
    OPPOPRICE BIGINT,
    APPLEPRICE BIGINT,
    SAMSUNGPRICE BIGINT,
    REDMIPRICE BIGINT,
    NOTHINGPRICE BIGINT,
    REALMEPRICE BIGINT,
    VIVOPRICE BIGINT,
    GOOGLEPRICE BIGINT,
    KARBONPRICE BIGINT,
    SONYPRICE BIGINT
);


CREATE DATABASE CARDITAILS;
USE CARDITAILS;

CREATE TABLE CAR1(
	BRAND VARCHAR(10),
	COLOR VARCHAR(10),
    PRICE BIGINT,
    CARSPEED INT(5),
    MODEL VARCHAR(6),
    YEAR INT(4),
    WHEEL INT(3),
    DISTANCE INT(4),
    MILAGE INT(6),
    FUEL VARCHAR(9)
    
);
 USE STUDENT;
 
 SELECT * FROM STUDENTDETAILS1;
 SELECT * FROM SANTHOM1;
 SELECT * FROM BRANDS;
 SELECT * FROM CAR1;








